on: [push]

jobs:
  test-everywhere:
    name: Test Action on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Run the action
        uses: fronix/mssqlsuite@v1.1
        with:
          install: sqlengine, sqlpackage
          sa-password: c0MplicatedP@ssword
          show-log: true
          port: "1454"

      - name: Run sqlcmd
        run: sqlcmd -S localhost,1454 -U sa -P c0MplicatedP@ssword -d tempdb -Q "SELECT @@version;"
